### ISSUE TITLE
PART 1 + Lesson 1 自选课程1 HTTP的请求和相应周期 练习10、11 链接问题

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#10]
![3](https://user-images.githubusercontent.com/7417557/34940050-15d0209c-fa29-11e7-9301-e2cc892a1c61.png)
![4](https://user-images.githubusercontent.com/7417557/34940207-a8466530-fa29-11e7-9c38-7e8cb26093f7.png)

[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8162118632/concepts/81883228140923](url)
[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8162118632/concepts/82168490640923](url)

描述： Google Developers 链接不翻墙打不开
建议：提供国内一些替代资源

**Comment by evestorm** [comment]
不科学上网确实打不开 `谷歌开发者平台` ，但对于那些可以访问墙外链接的同学来说还是有帮助的。所以不予删除。已添加一条国内替换资源。

感谢！
