### ISSUE TITLE
【翻译问题】Cache Response Quiz

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#100]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/83c4bddc-b362-4e71-8fa1-91f30ba57ab0/lessons/6381510081/concepts/63885494530923

## 截图
<img width="1444" alt="2018-02-09 6 01 56" src="https://user-images.githubusercontent.com/9304701/36022264-6ced3074-0dc3-11e8-81f7-2f8b60f1b107.png">

## 具体描述
00:37 -> `我们不需要上个任务中的任何特殊...处理代码` 

应改为：`我们不再需要上个作业中 404 响应的处理代码`

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
