### ISSUE TITLE
进阶 > 街机游戏>课程1 深入了解对象

### ISSUE THREAD

**Issue by BellaGuan** [udacity/fend-issues-zh#101]
### 重音字符指的是？
![1](https://user-images.githubusercontent.com/29974480/36639028-da758bba-1a3d-11e8-9ec3-4ce9e1b2999f.png)

### 图中的答案测试是对的喔，这问试不出正确答案……
![2](https://user-images.githubusercontent.com/29974480/36639039-10787222-1a3e-11e8-9528-8fcc4615084a.png)

### 最后一选项也正确吧，符合题意喔
![3](https://user-images.githubusercontent.com/29974480/36639047-36e667d4-1a3e-11e8-8351-9666f6aaaa39.png)

### 回答编辑不了
![4](https://user-images.githubusercontent.com/29974480/36639058-5fd51ea6-1a3e-11e8-9243-d3d24b82e5db.png)

### 这句表述不完整呢
![image](https://user-images.githubusercontent.com/29974480/36639011-70edee94-1a3d-11e8-9bef-7be3b8839480.png)

### 漏掉引号，改为["car", "apple", "cat", "dog"]
![image](https://user-images.githubusercontent.com/29974480/36639118-df574220-1a3f-11e8-908d-b82d097a9c0d.png)

### 这应该是指 for...in循环
![5](https://user-images.githubusercontent.com/29974480/36639059-61bb3822-1a3e-11e8-84b2-834f792a427a.png)

![image](https://user-images.githubusercontent.com/29974480/36639161-84b067b4-1a41-11e8-9cfb-b7382935c946.png)

**Comment by evestorm** [comment]
1. [accented characters](http://wiki.linuxquestions.org/wiki/Accented_Characters)
2. 正常情况下学生会输入 `mileTimes[3]` ，我们的检测只针对了最普遍的情况
3. 非常细心，已修改！
4. feature，这种类型的题目都只用回答一遍
5. 赞，已修改！
6. 已修改
7. 确实应该是 `for...in` ，已改正！

@BellaGuan 非常感谢指出了这么多细节上的问题，棒极了！
