### ISSUE TITLE
进阶 > 经典街机克隆 > 深入了解对象 > 创建和修改属性 

### ISSUE THREAD

**Issue by ghost** [udacity/fend-issues-zh#102]
[link](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/2bbcfed5-e683-431b-ace2-b67c091400d2)

![image](https://user-images.githubusercontent.com/25104361/36778188-fc8ddbba-1ca6-11e8-9a91-4330a947c47a.png)

这里1、3、4应该是正确答案，提交之后还是不正确

![image](https://user-images.githubusercontent.com/25104361/36778251-300f8e34-1ca7-11e8-8c69-1bc6e13bf9f0.png)

**Comment by evestorm** [comment]
fixed！
