### ISSUE TITLE
入门 > 记忆游戏 > 性能 > 4. 调用堆栈

### ISSUE THREAD

**Issue by tedlife** [udacity/fend-issues-zh#103]
## 截图

![image](https://user-images.githubusercontent.com/1589014/36929944-fbee0814-1ed2-11e8-94fd-5ead44ca2b7e.png)

## 具体描述

如图部分是多余的文字，并没有讲处理异步代码 ，英文版也没有这行文字
@sylviasun916 @Udacitymiaomiao @evestorm

**Comment by evestorm** [comment]
已修正！感谢 @tedlife ！
