### ISSUE TITLE
进阶 > 订阅阅读器测试 > 7. 总结 ：字幕格式出错

### ISSUE THREAD

**Issue by evestorm** [udacity/fend-issues-zh#107]
## 教室地址
进阶 > 订阅阅读器测试 > [7. 总结](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/cc9e0400-93ca-41a6-8493-571bc2ef981d/modules/8ca13c01-3730-42d5-96d7-88914cba61e4/lessons/5831700782/concepts/53580095540923?contentVersion=5.0.0&contentLocale=zh-cn)

## 截图
<img width="728" alt="scaffolding" src="https://user-images.githubusercontent.com/18142851/37448896-3465d688-2863-11e8-9360-afdf8f33c214.png">

## 描述
视频45s处字幕格式出错

**Comment by sylviasun916** [comment]
已修改 在部署中 感谢反馈！
