### ISSUE TITLE
Git课程中添加说明

### ISSUE THREAD

**Issue by addoilmai** [udacity/fend-issues-zh#108]
## 课程导航+地址
https://coco.udacity.com/nanodegrees/nd002-cn-advanced-career/locale/zh-cn/versions/2.0.0/parts/505099/modules/514276/lessons/339105/concepts/339070

## 具体描述
第一部分Git课程3“什么是版本控制”中，Mac/Linux设置部分，只提到了mac，但对于ubuntu应该是把设置信息复制到.bashrc文件中，而不是.bash_profile
学员建议加一行关于这个的说明，可以避免一些弯路

**Comment by evestorm** [comment]
已更新~
