### ISSUE TITLE
入门 > 作品集 >7-9 练习：设置窗口

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#109]
## 课程导航+地址
入门 > 作品集 > 7. 从小处开始 > [9. 练习：设置窗口](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/ae453d5e-519a-4f2f-a8ac-b7a917639b62/modules/8a732382-f993-4486-9380-14aee2ab9d71/lessons/3494350031/concepts/35260393050923)

## 截图
https://d.pr/i/piI5UF

## 具体描述
缺少讲师注释

**Comment by evestorm** [comment]
@DonaldDai 感谢反馈！已修复！
