### ISSUE TITLE
缺少练习链接

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#111]
## 课程导航+地址
入门 > 作品集 > 7.从小处开始 > [16. 欢迎](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/ae453d5e-519a-4f2f-a8ac-b7a917639b62/modules/8a732382-f993-4486-9380-14aee2ab9d71/lessons/3494350031/concepts/35019794250923)

## 截图
Null

## 具体描述
视频中的练习页面文件缺少，记得以前有个github链接

**Comment by evestorm** [comment]
已修复！
