### ISSUE TITLE
solution.html 有笔误

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#114]
## 课程导航+地址
例子：入门 > 动物卡片 > 样式表链接 > [12.样式表链接](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/f315b961-07c6-4a0a-9fb8-f4265dfb1ea1/modules/f2a8da8d-c191-41c5-a7b9-69850a1f6a88/lessons/7323812069/concepts/d8bd4777-cc82-46e7-bb3f-8649ca07f846)

## 截图
![wechatimg405](https://user-images.githubusercontent.com/14327519/40301967-474d6f80-5d20-11e8-9ad0-06d17d47e4bd.jpeg)

## 具体描述
见上图

**Comment by evestorm** [comment]
已修复
