### ISSUE TITLE
课堂练习 workshop 打开大概率连接超时

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#115]
## 课程导航+地址
入门> 动物卡片 > css 语法习题集 > [6. 属性workshop](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/f315b961-07c6-4a0a-9fb8-f4265dfb1ea1/modules/f2a8da8d-c191-41c5-a7b9-69850a1f6a88/lessons/7323812069/concepts/c13e1ee7-4be8-42ef-85e3-e7060e9e65c2#)

## 截图
![image](https://user-images.githubusercontent.com/14327519/40413960-b44320d2-5ea9-11e8-9001-7ff3e10e8084.png)

## 具体描述
workshop 打开大概率超时

**Comment by evestorm** [comment]
workspace问题是classroom整体的问题，因为服务器不在国内。暂时没法儿修复，只能安抚学员或者让学员科学上网 @DonaldDai
