### ISSUE TITLE
像素画 > 查看仓库的历史记录 > [查看文件更改] git 课程表述不清晰

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#116]
## 课程导航+地址
例子：入门 > 像素画 > 查看仓库的历史记录 > [查看文件更改](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/fde0b578-2d1a-4e35-910e-a7e3a8c24139/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/280d5ccf-6440-4d27-97d1-d9f6118359bc/concepts/dac0d8d4-e9a0-4b6e-bf65-f2d8e7a434c8)

## 截图
![image](https://user-images.githubusercontent.com/14327519/42196128-da64b24c-7eae-11e8-82a2-10d56ee1aedb.png)

## 具体描述
此处表述不准确，应该是显示83行，而不是文件有83行，下面那行句子也需相应的修改

**Comment by evestorm** [comment]
已修复！
