### ISSUE TITLE
作品集 > CSS框架和响应式布局 > CSS重设 链接失效

### ISSUE THREAD

**Issue by DonaldDai** [udacity/fend-issues-zh#120]
## 课程导航+地址
作品集 > CSS框架和响应式布局 > [CSS重设](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/ae453d5e-519a-4f2f-a8ac-b7a917639b62/modules/a118bf78-c87c-40d1-bf5a-dd446ba1cfd5/lessons/2810388540/concepts/28721985670923)

## 截图
![image](https://user-images.githubusercontent.com/14327519/42405853-bdb464d4-81cf-11e8-8cd9-22f2c8064c03.png)

## 具体描述
此 normalize.css 链接已失效，建议在视频下方提供最新链接
necolas.github.io/normalize.css/8.0.0/normalize.css
或者获取最新链接的方法（搜索引擎 normalize.css ）

**Comment by evestorm** [comment]
已修复，感谢zhilian~
