### ISSUE TITLE
课程内容同时存在 > 和 ``` 时会有语法混乱的情况

### ISSUE THREAD

**Issue by ivylee0919** [udacity/fend-issues-zh#127]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 课程 1: 深入了解对象 > [1. 简介](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/409c8e65-59c6-4d67-8ea8-6934fad5ab0b)

## 截图
![34ff450ea88adca684dbbc3a9cbf87d](https://user-images.githubusercontent.com/11519486/45739427-91c1a900-bc25-11e8-8274-ce30ac8f027b.png)

## 具体描述
@evestorm 
不只这一处出现问题，在入门的课程中也多次出现这样的情况，英文版本同样存在问题。
建议这样的情况下，将前面的 `>` 删除。

**Comment by ivylee0919** [comment]
与上面同一小节的下半部分内容：
![image](https://user-images.githubusercontent.com/11519486/45740864-c84cf300-bc28-11e8-814e-38f1a7772988.png)

**Comment by evestorm** [comment]
fixed，Thx @ivylee0919
