### ISSUE TITLE
HTTP's Request/Response Cycle --- 字幕修改建议

### ISSUE THREAD

**Issue by Xeonice** [udacity/fend-issues-zh#15]
HTTP's Request/Response Cycle（（897）进阶选修 - 客户端服务器通信） 修改建议

-----------------------------

locales/zh-cn/1KF0jkNj7sg.srt ---> (Fetch Quiz)

 3
 00:00:04,799 --> 00:00:06,879
-并应对不必要的复杂功能
+与它不必要的复杂功能
 
-----------------------------

locales/zh-cn/GVsmyc3MVp8.srt ---> (Answer: DevTools Quiz)
 
 2
 00:00:01,649 --> 00:00:04,049
-并位于 Network 标签页上
+并切换到了 Network 标签页
 
 4
 00:00:06,080 --> 00:00:07,810
-网页被加载时的整个概览
+整个网页被加载时的概况
 
 6
 00:00:10,480 --> 00:00:13,490
-并包含每个请求的信息
+以及每个请求所包含的信息
 
-----------------------------

locales/zh-cn/HBmOROFs8WM.srt ---> (Introduction)
 
 9
 00:00:18,539 --> 00:00:19,919
 -这是一门网络课程
 +这是一门 web 课程

 10
 00:00:19,920 --> 00:00:23,670
 -从技术上来说 网络只是互联网的一小部分
 +从技术上来说 web 只是互联网的一小部分

 11
 00:00:23,670 --> 00:00:25,530
-但是 它也是人们在使用时
+但是 这也是唯一一种
 
 12
 00:00:25,530 --> 00:00:27,960
-唯一没有意识到正在使用的是网络的
+人们在使用时甚至意识不到它的存在的
 
 13
 00:00:27,960 --> 00:00:30,219
-互联网部分
+互联网
 
 14
 00:00:30,219 --> 00:00:33,089
-网络是一种可以被网络开发者用于
+web 是一种可以被网络开发者用于
 
 20
 00:00:47,130 --> 00:00:48,740
 -你都用到了网络
 +你都用到了 web

 21
 00:00:48,740 --> 00:00:50,789
-或者更一般的情况 在此刻
+或者更常见的情况 此时此刻
 
 26
 00:01:01,670 --> 00:01:04,420
 -网络有什么功能 更重要的是
 +web 有什么功能 更重要的是

 32
 00:01:11,909 --> 00:01:13,859
-在这门课程中 我们将了解到底什么是网络
+在这门课程中 我们将了解到底什么是 web

 33
 00:01:13,859 --> 00:01:17,370
 -如何利用网络以发挥你的优势
 +如何利用 web 以发挥你的优势
 
 34
 00:01:17,370 --> 00:01:20,130
-以及如何避免影响到
+以及如何避免那些会影响到
 
 35
 00:01:20,129 --> 00:01:23,219
-用户体验和安全性的问题
+用户体验和安全性的错误
 
 38
 00:01:30,132 --> 00:01:31,590
-要像工程师一样思考问题
+为了像工程师一样思考问题
 
 41
 00:01:38,219 --> 00:01:41,189
-我们将运用这些知识重复利用浏览器 API
+我们将运用这些知识 调用浏览器 API 以充分发挥它的潜力

 43
 00:01:44,700 --> 00:01:48,390
 -并部署最新的网络协议——HTTP2
 +并部署最新的 web 协议——HTTP2
 
 45
 00:01:51,060 --> 00:01:54,540
-并鼓励其他人优化他们的应用
+同时鼓励其他人优化应用 提高
 
 46
 00:01:54,540 --> 00:01:56,609
-和提高应用安全性
+应用的安全性
 
 -----------------------------

locales/zh-cn/NU-Oo6n-4DQ.srt ---> (Outro)
 
 3
 00:00:06,299 --> 00:00:09,289
-以及当你访问网站时 浏览器真正执行的操作
+以及当你访问网站时 浏览器实际执行的操作
 
 4
 00:00:09,289 --> 00:00:11,639
-你知道元数据如何关联到请求和响应上
+你知道如何将元数据关联到请求和响应上
 
 -----------------------------

locales/zh-cn/NVQMhvwULJU.srt ---> (Answer: Fetch Quiz)
 
 4
 00:00:07,950 --> 00:00:12,419
-并且需要同时发送 X-Udacity-Exercise
+并且需要同时发送标头 X-Udacity-Exercise
 
 -----------------------------

locales/zh-cn/_dVf8u0BIvM.srt ---> (Getting Multiple Requests)

 4
 00:00:07,299 --> 00:00:09,140
 -但是在网络上 一切通常都以
 +但是在 web 上 一切通常都以^M

 11
 00:00:22,160 --> 00:00:24,920
-打开由 URL 主机名标识的
+通过 URL 辨识出服务器的主机名
 
 12
 00:00:24,920 --> 00:00:28,730
-指向服务器的新链接
+并与它建立新链接
 
 13
 00:00:28,730 --> 00:00:30,679
-并获得 URL 的路径中指定的文档
+随后获得 URL 的路径中指定的文档
 
 26
 00:00:58,340 --> 00:01:01,040
-这些文档包括图片 样式表 JavaScript 文件
+例如图片 样式表 JavaScript 文件
 
 28
 00:01:02,539 --> 00:01:06,079
-对于每种资源 发出另一个请求
+对所有这些资源 发出另一个请求
 
 30
 00:01:09,109 --> 00:01:12,200
-就会重复整个解析和潜在地发送
+就会重复整个解析和可能存在的发送
 
 33
 00:01:17,390 --> 00:01:20,450
-可以获取其他资源
+都可以反过来获取其他资源
 
 34
 00:01:20,450 --> 00:01:22,280
-每个着陆页都有自己的一组依赖项
+每个网页都有自己的一组依赖项
 
 37
 00:01:28,400 --> 00:01:32,530
-可能会触发比你想象的要多的请求
+所发送的请求可能比你想象中要多得多

-----------------------------

locales/zh-cn/dNdBbnCj_e4.srt ---> (HTTP Requests 2)
 
 5
 00:00:11,250 --> 00:00:14,609
-原始的协议（后来称之为 0.9）
+原始的协议（后来被称为 HTTP 0.9）
 
 7
 00:00:16,379 --> 00:00:18,390
-如果你想检索或存储文档 则需要填写该模板
+你需要在模板中填入你希望获取或存储的文档
 
 8
 00:00:18,390 --> 00:00:20,368
-将文档存储到何处
+存储文档的位置
 
 9
 00:00:20,368 --> 00:00:22,410
-包括名称和任何其他
+包括名称和所有
 
 10
 00:00:22,410 --> 00:00:25,410
-你认为必要的信息
+你认为必要的额外信息
 
 11
 00:00:25,410 --> 00:00:27,990
-该请求然后被发送至服务器
+随后 该请求被发送至服务器
 
 14
 00:00:32,850 --> 00:00:34,980
-从而知道客户端想要什么
+从而知道客户端想要什么

 15
 00:00:34,979 --> 00:00:37,979
-该协议还具有响应模板
+该协议还有响应模板

-----------------------------

locales/zh-cn/jf2-_10CcAg.srt ---> (HTTP Requests)
 
 7
 00:00:15,630 --> 00:00:17,760
-他希望有一种机制能够让研究者
+他希望有一种开放机制 能够让研究者
 
 10
 00:00:23,429 --> 00:00:25,679
-称为超文本文档
+即超文本文档
 
 11
 00:00:25,679 --> 00:00:27,809
-Berners-Lee 选择了一部分 SGML
+Berners-Lee 选择了 SGML 的一个子集
 
 20
 00:00:51,329 --> 00:00:54,879
-而且可以通过这些链接访问相关的文档
+而且可以通过这些链接访问其他相关文档
 
 22
 00:00:56,520 --> 00:00:58,410
-所设计的科学环境下
+所设计的细致严谨的环境下
 
 25
 00:01:03,450 --> 00:01:08,060
-文件还可以链接到图片 代码 样式或任何其他内容
+还可以链接到图片 代码 样式等文件或任何其他内容

-----------------------------

locales/zh-cn/ra4PkyTeQR4.srt ---> (Sending data with a POST Request)
 
 9
 00:00:19,710 --> 00:00:21,780
-有效负荷或主体
+有效载荷或主体
 
 10
 00:00:21,780 --> 00:00:25,679
-我们之前在响应中已经见过 但是没在请求中见过
+即那些我们之前在响应中已经见过 但是没在请求中见过的东西
 
 11
 00:00:25,679 --> 00:00:27,780
-数据被发送至服务器后发生的情况
+数据被发送至服务器后的具体处理流程
 
 17
 00:00:40,439 --> 00:00:42,269
-见过这个页面吗？
+见过这种情况吗？
 
 20
 00:00:47,880 --> 00:00:50,310
-如果你尝试上传此类网站
+如果你尝试重新加载此类网站
 
 21
 00:00:50,310 --> 00:00:53,490
-浏览器将提示你确认是否执行此重新加载操作
+浏览器将提示你确认是否执行重新加载操作
 
 22
 00:00:53,490 --> 00:00:56,730
-因为 POST 请求可以是销毁性操作
+因为 POST 请求可以是破坏性操作
 
 23
 00:00:56,729 --> 00:01:00,239
-重复执行的销毁程度可能比你想象的
+重复执行的破坏性可能比你想象的
 
 -----------------------------
 
locales/zh-cn/s5-ctaI8qVM.srt ---> (Fetching a single request)
 
 6
 00:00:15,869 --> 00:00:17,579
-这正是浏览器为了请求叫做 kitty.jpg 的图片
+这是浏览器为了请求图片
 
 7
 00:00:17,579 --> 00:00:21,479
-向服务器发送的文本
+kitty.jpg 而向服务器发送的详细文本
 
 8
 00:00:21,480 --> 00:00:23,399
-我们详细了解下第一行
+我们深入了解下第一行
 
 12
 00:00:31,829 --> 00:00:34,059
-要区分这些功能
+为了区分这些功能
 
 13
 00:00:34,060 --> 00:00:38,320
-第一行以一个 HTTP 方法（即一个动词）开头
+协议的第一行以一个 HTTP 方法（即一个动词）开头
 
 -----------------------------

locales/zh-cn/wGUUGW-Su3k.srt ---> (From XHR to Fetch)
 
 3
 00:00:04,620 --> 00:00:06,629
-经常我们一开始不知道想要什么
+我们不会总是一开始就知道想要什么
 
 6
 00:00:10,115 --> 00:00:11,490
-我们不知道当用户未来访问该网站时
+我们不知道
 
 7
 00:00:11,490 --> 00:00:14,460
-天气会怎样
+用户在未来访问该网站时的天气如何
 
 9
 00:00:16,440 --> 00:00:18,960
-可能需要的所有图片
+所有可能需要的图片

 12
 00:00:24,817 --> 00:00:26,699
-Ajax 是一系列的网络技术
+Ajax 是一系列的 web 技术
 
 23
 00:00:56,789 --> 00:00:59,189
-但是 API 利用了 promise 更加整洁
+但是利用了 promise 的 API 更加整洁
 
 29
 00:01:10,409 --> 00:01:13,019
-借助 Fetch 你可以利用协议指定的所有 HTTP 方法
+借助 Fetch 你可以调用协议指定的所有 HTTP 方法
 
 32
 00:01:18,030 --> 00:01:20,390
-当然几乎包括所有的标头
+当然包括几乎所有的标头
 
 -----------------------------

locales/zh-cn/xoYE2LIcVz0.srt ---> (DevTools Quiz)
 
 14
 00:00:31,550 --> 00:00:32,990
-或在 Windows 上按下 Control+Shift+I
+或在 Windows 上按下 Ctrl+Shift+I
 
 16
 00:00:35,210 --> 00:00:38,420
-该服务器的二进制文件位于以下的资源下载部分
+该服务器的二进制文件位于下面的资源下载部分

**Comment by Xeonice** [comment]
PR 已提交 --> https://github.com/udacity/subtitles/pull/2569

**Comment by sylviasun916** [comment]
好棒！！！感谢反馈和修改！！！
