### ISSUE TITLE
入门选修 - 构建高转化率页面表单>课程1.高效输入1  

### ISSUE THREAD

**Issue by BellaGuan** [udacity/fend-issues-zh#18]
- 需要翻墙的课外链接感觉可以备注一下来提醒学员，这样的话，一些没经验的学员就不会以为链接失效。如果能提供翻墙指导文档也不错，我只用过lantern；
- 翻建=翻译建议；
- 数字编号指代着第几小节

1. 课程简介
翻建：Chrome的使用数据表明…
<此处应该有图片，太多图片了，传得好懵，点击下面的链接可以看到更详细的叙述>
[点我，在有道云笔记里…](http://note.youdao.com/noteshare?id=e6802ac5c9784ebe00b57d6ad08a79e3&sub=F8ED9A60F314464DB7B97D11D4C8C70C)

**Comment by evestorm** [comment]
@BellaGuan 棒棒的！！！

p.s. 下次就直接在github上传吧，假如是同一个视频当中的问题，可以汇总提交成一个issue；如果是两个视频当中的问题，可以提两个issue~  这次我就重新把你提供的反馈整理一下啦！再次感谢~

**Comment by evestorm** [comment]
@sylviasun916 上面issue [有道笔记](https://note.youdao.com/share/?id=e6802ac5c9784ebe00b57d6ad08a79e3&type=note#/) 链接中包含一些字幕翻译问题，对应修改下吧~

**Comment by sylviasun916** [comment]
@BellaGuan 收到，非常感谢！

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
