### ISSUE TITLE
入门：构建高转化率页面表单>课程1>高效输入1>课程简介

### ISSUE THREAD

**Issue by evestorm** [udacity/fend-issues-zh#19]
![课程简介](https://note.youdao.com/yws/public/resource/e6802ac5c9784ebe00b57d6ad08a79e3/xmlnote/D78A59264750428FA92025E3FD466E66/11153)

翻译建议：`Chrome的使用数据表明…` 

---

![课程简介](https://note.youdao.com/yws/public/resource/e6802ac5c9784ebe00b57d6ad08a79e3/xmlnote/2442DF8B675142D193EDD4A0D59509C5/11173)

翻译建议：`因此在这节课中  我们会更侧重移动设备的表单开发`

---

![课程简介](https://note.youdao.com/yws/public/resource/e6802ac5c9784ebe00b57d6ad08a79e3/xmlnote/B50748697AAA449FA9E02B935E1375C7/11217)

翻译建议：`你将学习构成表单的input组件，它包括……`

**Comment by sylviasun916** [comment]
已修改，谢谢建议！
