### ISSUE TITLE
入门：构建高转化率页面表单>课程1>高效输入1>修正表单

### ISSUE THREAD

**Issue by evestorm** [udacity/fend-issues-zh#20]
以为红色框链接是到 优达论坛，建议：改为“这是视频中提到的表单”

![修正表单](https://note.youdao.com/yws/public/resource/e6802ac5c9784ebe00b57d6ad08a79e3/xmlnote/8EFACE6491284DB2A64D794BD1FE750A/11259)

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
