### ISSUE TITLE
PART 1 + Lesson 1 自选课程 课程2 练习2 链接问题 

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#23]
<img width="1272" alt="2018-01-17 9 30 28" src="https://user-images.githubusercontent.com/7417557/35045304-56392cb8-fbce-11e7-970c-4effcc319a23.png">

[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8080328065/concepts/81948027770923](url)

问题描述：延伸阅读第一个链接错误。
建议：更换链接地址

**Comment by evestorm** [comment]
很细心！已修正！
