### ISSUE TITLE
入门选修 - 构建高转化率页面表单>课程2.高效输入2

### ISSUE THREAD

**Issue by BellaGuan** [udacity/fend-issues-zh#25]
### 4、8、9、13、14、16、18（这是节数，代表第4小节、第8小节、第9小节……都出现mozilla的英文链接）
- 凡是mozilla的英文链接，可以考虑改成中文链接，或者在入门课程的第一篇mozilla课外资料就教学员如何转换mozilla的语言版本，省心~

### 3.标签~
- 英文字幕错误，应该是for
![31](https://user-images.githubusercontent.com/29974480/35045851-289a77ce-fbd0-11e7-8127-c64ac5831ec9.png)

- 中文错误，for是属性，不是元素。中文应该是“form元素”
![32](https://user-images.githubusercontent.com/29974480/35045921-620fed18-fbd0-11e7-9f7a-ce9c18db6c59.png)

### 5.访谈
- 中文可改为”[名称:值]对“、”名值对”或“键值对“，因为读得顺口，看得形象……如果改的话，这段视频里还有好多处”名称值对“需要更改。
![51](https://user-images.githubusercontent.com/29974480/35046013-b6981428-fbd0-11e7-9c6a-3a85b9f1b90d.png)

### 9.日历
英文单词错误，更正为：‘datetime-local’
中文错误，可更改为：type="datetime-local"
![91](https://user-images.githubusercontent.com/29974480/35049151-0b4dd26a-fbda-11e7-881d-0b9bdd199685.png)

- 这是英文参考文档的中文版本https://www.w3cplus.com/css3/list-of-pseudo-elements-to-style-form-controls.html
- **10.练习**也有这个英文参考文档，也需要替换
![image](https://user-images.githubusercontent.com/29974480/35050935-f9d57a60-fbde-11e7-8b2e-d631452e5960.png)

### 12.自动填充
- 英文错误，标点符号用错了；
- 中文可改为：”叫做autofill，即是自动填充“
![121](https://user-images.githubusercontent.com/29974480/35049948-96676274-fbdc-11e7-9154-dcc20d836b3a.png)

- 这段视频好多处是直接将autofill翻译成自动填充，但我觉得在导师指代某个元素时，应该不翻译该单词，比如下图中的中文译为”name属性和autocomplete属性“；只有指代其意思时，才翻译成中文。
![image](https://user-images.githubusercontent.com/29974480/35051397-17248f24-fbe0-11e7-8610-843736a66778.png)

- 这样的中文翻译也挺好的
![image](https://user-images.githubusercontent.com/29974480/35058043-ad91948c-fbf1-11e7-9562-b528a6167e9a.png)

### 13.练习~
- 英文错误，应该是Ido 
![image](https://user-images.githubusercontent.com/29974480/35052284-2ba333e0-fbe2-11e7-81d9-14f7a2e5abd7.png)

### 16.验证
- 英文错误and改a
![image](https://user-images.githubusercontent.com/29974480/35058742-d9d83616-fbf3-11e7-8cb2-7ce268db6a1b.png)

**Comment by evestorm** [comment]
@sylviasun916 内容方面的问题我已经修正啦，字幕的问题需要你费心啦

**Comment by sylviasun916** [comment]
已修改，谢谢！
