### ISSUE TITLE
进阶：订阅器 课程1简介

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#28]
### 练习：成本效益
最好把练习页面的内容也翻译到下面去哦=_=这样会非常照顾英语基础差的学员呢
![d2vt 1 lf qx px 4 isk](https://user-images.githubusercontent.com/24735241/35097636-f435d61a-fc8b-11e7-96b8-5768f4ddfbf6.png)
### 课程3 常识
4个标题的字幕翻译缺失，最好在字幕里面加上哈
![7v t9f qq64axnr9gvck5 e](https://user-images.githubusercontent.com/24735241/35097741-5c5adc68-fc8c-11e7-9215-6bfe8329367a.png)
![zd1b5kn_v6y yq0i 1 5](https://user-images.githubusercontent.com/24735241/35097760-69bd79a6-fc8c-11e7-969a-dc6f69f2c8a0.png)
![m ean zac8dz_mi6syb5n4](https://user-images.githubusercontent.com/24735241/35097783-8566cd92-fc8c-11e7-95f6-c45227739df2.png)
![8o 4 22co 4g0i51 5nlnxd](https://user-images.githubusercontent.com/24735241/35097798-a0fd2b0a-fc8c-11e7-9111-5106776738f5.png)

**Comment by sylviasun916** [comment]
@evestorm

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
