### ISSUE TITLE
进阶： 订阅器 课程2 高效编辑器

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#29]
### 6快捷键
应该是翻译人员有点粗心哈=_=虽然说学员肯定能够知道他说的是啥，但是翻译还是改改吧
![2x m uxd o cc_k_mwc0g4](https://user-images.githubusercontent.com/24735241/35137614-34e5d978-fd25-11e7-8c04-5e9e820f5ae8.png)

**Comment by sylviasun916** [comment]
的确是翻译公司粗心了，感谢反馈！谢谢
