### ISSUE TITLE
自选课程 课程3 2 加密http 链接错误

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#31]
![image](https://user-images.githubusercontent.com/7417557/35148697-298a06ac-fd4e-11e7-9415-55fefe564c71.png)

[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8150909334/concepts/82548188640923](url)

问题描述：第一个链接错误
建议：修改链接

**Comment by evestorm** [comment]
@eruerua 已修正！THX~
