### ISSUE TITLE
自选课程 课程3 13 练习 字幕显示错误

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#32]
![image](https://user-images.githubusercontent.com/7417557/35150045-9ee80494-fd53-11e7-8f37-1441bb284297.png)

[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8150909334/concepts/c7198c5a-e465-4cde-a72b-56a37e88c72c](url)

问题描述：字幕显示错误，应该只显示一行

**Comment by sylviasun916** [comment]
已修改，在部署中，谢谢反馈！
