### ISSUE TITLE
进阶： 订阅器 课程4 体验实时编辑

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#33]
### 4.使用browser-sync
建议将第三小节的链接内容也放到这一节的下面哦=_=这样会很方便
![afyb_7 l om2 a lb hc4u2](https://user-images.githubusercontent.com/24735241/35179298-a999e3d8-fdd2-11e7-9bd9-3eddf4fcfe25.png)

### 内容修改建议
此外，我觉得应该更详细地向观众说明这一节的具体内容
**（原）**
1.安装 browser-sync.
2.创建一个浏览器同步对象并初始化服务器。
```javascript
var browserSync = require('browser-sync').create();
 browserSync.init({
     server: "./"
 });
 browserSync.stream();
 ```
3.在终端中运行 gulp，看看浏览器如何打开页面。
**（改）**
1.安装 browser-sync.
```javascript
npm install -g browser-sync
```
2.创建一个浏览器同步对象并初始化服务器。
```javascript
var gulp = require('gulp');
gulp.task('default', defaultTask);
function defaultTask(done) {
  var browserSync = require('browser-sync').create();
	browserSync.init({
               // 这里的意思是含有这个文件的目录地址，可以将目录更改
		server: "./"
	});
	browserSync.stream();
  done();
}
```
3.在终端中运行 gulp，看看浏览器如何打开页面。

**Comment by evestorm** [comment]
@BrainChen 已优化！
