### ISSUE TITLE
进阶： 订阅器 课程5 如何免受灾难

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#34]
### 4.练习：linting如何帮助你编程 **翻译缺失**
这个课程练习没有相应的翻译哦=_=建议在下面提供哈
https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/cc9e0400-93ca-41a6-8493-571bc2ef981d/modules/8ca13c01-3730-42d5-96d7-88914cba61e4/lessons/5876358842/concepts/53738292230923
![c 6w_ 1t oeqc yjaeudd](https://user-images.githubusercontent.com/24735241/35180796-067c3ee2-fdf2-11e7-91a3-6a6f5c9c5165.png)

**Comment by sylviasun916** [comment]
已修改，非常感谢谢反馈！

**Comment by sylviasun916** [comment]
已修改，非常感谢谢反馈！
