### ISSUE TITLE
入门选修 > 构建高转化率页面表单>课程3更快的表单

### ISSUE THREAD

**Issue by BellaGuan** [udacity/fend-issues-zh#36]
### 鼠标hover或focus按钮，按钮会隐藏，但按钮功能还在~
![image](https://user-images.githubusercontent.com/29974480/35185965-5816245c-fe47-11e7-984d-d1cb1c88261c.png)

### 从截图所示的时间开始，字幕跟不上音频和视频。
![image](https://user-images.githubusercontent.com/29974480/35185543-2361e0bc-fe41-11e7-8cd5-98cc1982756d.png)

### 中文可改为[名:值]对。ps：同上一课的name-value pair的翻译保持一致吧，可翻之前的issue。
![image](https://user-images.githubusercontent.com/29974480/35185759-218b36fa-fe44-11e7-9a6b-8122e1716150.png)

### 中文可改为”网络上看着奇怪的互动“。ps：觉得这样翻译后还是点啥。。。
![image](https://user-images.githubusercontent.com/29974480/35185832-1fb60700-fe45-11e7-86bd-30eefb7edc2a.png)

### 中文表述不恰当，ps：哎我不知道怎么翻译，译成”什么信息需要向用户解释“？
![clipboard](https://user-images.githubusercontent.com/29974480/35186241-fe493540-fe4b-11e7-870b-9edd0dcddc8b.png)

### 英文分别是Geolocation , autofill , Autofill
![image](https://user-images.githubusercontent.com/29974480/35186232-dd1db1f2-fe4b-11e7-8a47-6006db785103.png)
![image](https://user-images.githubusercontent.com/29974480/35186256-2d050eea-fe4c-11e7-8edd-77373047cc2f.png)
![image](https://user-images.githubusercontent.com/29974480/35186322-29a905b6-fe4d-11e7-871d-20915a92461c.png)

### MDN可改中文版本
![image](https://user-images.githubusercontent.com/29974480/35186317-1793c578-fe4d-11e7-8222-523bb887147a.png)

### 辅助材料都需要翻墙下载
![image](https://user-images.githubusercontent.com/29974480/35186368-f0ea0364-fe4d-11e7-9e11-7648a0194cbc.png)

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
