### ISSUE TITLE
PART 经典街机游戏 + Lesson 2 Focus 18.小结

### ISSUE THREAD

**Issue by BranDanny** [udacity/fend-issues-zh#38]
![2018-01-21_213527](https://user-images.githubusercontent.com/27321353/35194759-8749f7f6-fef3-11e7-9023-08b675b9872d.png)

当背景音无意义且不影响理解时, 建议去掉字幕
链接:https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962031279/concepts/79640216360923

**Comment by sylviasun916** [comment]
已修改为 [背景音], 方便同学在特殊情况下，如音量调低时依旧可以看到字幕来理解。谢谢反馈！
