### ISSUE TITLE
PART 经典街机游戏 + Lesson 3 Semantics Basics 14.练习

### ISSUE THREAD

**Issue by BranDanny** [udacity/fend-issues-zh#39]
![2018-01-21_220742](https://user-images.githubusercontent.com/27321353/35194999-dbbab5b0-fef7-11e7-9802-54ae73e2aeab.png)

此处未翻译

**Comment by sylviasun916** [comment]
@evestorm 可以发给我链接么…… 没有链接我很难排查出来

**Comment by sylviasun916** [comment]
已修改，非常感谢反馈！
