### ISSUE TITLE
入门选修 > 构建高转化率页面表单>课程4 触摸支持

### ISSUE THREAD

**Issue by BellaGuan** [udacity/fend-issues-zh#40]
- 翻译有点难懂，不知道怎么改
- 链接可备注翻墙
![image](https://user-images.githubusercontent.com/29974480/35194422-5843c9dc-feee-11e7-95bb-d9f1688d1c11.png)

###  人名不对应，应是Ido
![image](https://user-images.githubusercontent.com/29974480/35194556-6b656ca8-fef0-11e7-8e0b-ebcd403b6f8d.png)

###  两个链接可备注翻墙
![image](https://user-images.githubusercontent.com/29974480/35194631-470a0750-fef1-11e7-9d0f-512b43924712.png)

###  英文错误，应是touchend
![image](https://user-images.githubusercontent.com/29974480/35195663-ee75d9dc-ff01-11e7-999f-e02dce1eef40.png)
![image](https://user-images.githubusercontent.com/29974480/35195919-b710deca-ff05-11e7-9648-ea6fc69b6718.png)

###  中文可改为“原生JavaScript”
![image](https://user-images.githubusercontent.com/29974480/35195682-2be7d266-ff02-11e7-9576-e3312792e21e.png)

![image](https://user-images.githubusercontent.com/29974480/35196169-6482ce26-ff09-11e7-9ea9-55717d41bf1f.png)

![image](https://user-images.githubusercontent.com/29974480/35196178-81c81a4a-ff09-11e7-92e3-716662d28487.png)

![image](https://user-images.githubusercontent.com/29974480/35196180-8eee2d36-ff09-11e7-943d-3987c3193ea4.png)

![image](https://user-images.githubusercontent.com/29974480/35196185-a19dae34-ff09-11e7-8135-60008e7974de.png)

![image](https://user-images.githubusercontent.com/29974480/35197216-56bb4724-ff17-11e7-8e2c-ff76b1acd8b7.png)

###  中文可改为“事件监听器的代码结构” 
![image](https://user-images.githubusercontent.com/29974480/35195711-8a54829a-ff02-11e7-931f-9eaa57c10322.png)

###  英文错误，改为a DOM node 
![image](https://user-images.githubusercontent.com/29974480/35195884-0640db22-ff05-11e7-9943-566c4882738e.png)

###  中文可改为：将被浏览器传递一个事件对象（event object）
![image](https://user-images.githubusercontent.com/29974480/35195957-573fa016-ff06-11e7-90a0-f11b2a006447.png)

###  中文可改为：事件对象是回调函数的唯一参数
![image](https://user-images.githubusercontent.com/29974480/35195963-7fe6c760-ff06-11e7-809e-d203fd40d1f9.png)

###  中文理解起来有点难度，改为“触点”。请参考MDN的解释：
- TouchEvent.changedTouches ：一个 TouchList 对象，包含了代表所有从上一次触摸事件到此次事件过程中，状态发生了改变的触点的 Touch 对象。
- targetTouches ：一个 TouchList 对象，是包含了如下触点的 Touch 对象：触摸起始于当前事件的目标 element 上，并且仍然没有离开触摸平面的触点。
- touches ：一 个 TouchList 对象，包含了所有当前接触触摸平面的触点的 Touch 对象，无论它们的起始于哪个 element 上，也无论它们状态是否发生了变化。
![image](https://user-images.githubusercontent.com/29974480/35197023-1e79cda6-ff15-11e7-9de7-2908d8f276ea.png)

###  10 .最终项目的说明……
  ● firebase.的链接觉得可以备注“翻墙”
  ● 检查清单 是全英滴～

###   11.课程总结
中文翻译有点拗口，可改为“最重要的是 在往后的表单开发中  你拥有正确地解决表单问题的思维”
![23](https://user-images.githubusercontent.com/29974480/35197059-7c863db2-ff15-11e7-9f38-9874ab0aaa8b.png)

**Comment by evestorm** [comment]
@sylviasun916 [此链接](https://classroom.udacity.com/nanodegrees/nd001-cn-basic/parts/156e7f5b-2a7b-4a94-816e-5b821970aa64/modules/71e66a37-d215-42e2-b547-15535d99071b/lessons/5243961825/concepts/54476086290923)最后有两个图片，全英文的。可以翻译成文本形式发给我吗？

**Comment by sylviasun916** [comment]
已修改，非常感谢反馈！
