### ISSUE TITLE
入门选修 > 构建高转化率页面表单>课程4 触摸支持 > 8访问 >中文字幕错误

### ISSUE THREAD

**Issue by GongJS** [udacity/fend-issues-zh#41]
![1516583341](https://user-images.githubusercontent.com/25744301/35201206-711fa4d8-ff54-11e7-97d5-96b72b7833a9.png)

“所有人一眼”，应该改成“所有人一样”。

**Comment by sylviasun916** [comment]
已修改，在部署中，谢谢反馈！
