### ISSUE TITLE
入门： 记忆游戏 19文档对象模型 课程链接

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#50]
建议将这一节所有课程的链接到MDN文档的内容，英文版换成中文版的链接（将链接中的en-US换成zh-CN就好）
以下是其中一个课程的示例：
![dxm1rgs o48s2 kef 3dcb](https://user-images.githubusercontent.com/24735241/35374249-09a94c74-01dd-11e8-98cc-de11ad5df7ef.png)

**Comment by evestorm** [comment]
@BrainChen 感谢反馈，JavaScript和DOM课程中的所有MDN链接已全部修改为zh-CN
