### ISSUE TITLE
入门： 记忆游戏 21使用浏览器事件 视频播放

### ISSUE THREAD

**Issue by pakeypay** [udacity/fend-issues-zh#51]
问题：同一个页面可以同时播放多个视频

![yun2](https://user-images.githubusercontent.com/7994218/35404771-0bc1e950-023f-11e8-96be-d7529fb4e5b7.jpg)

建议：建议只播放，最后点击播放的那个。

**Comment by evestorm** [comment]
这种场景出现的频率略低呀...  不过我会先记录下来的
