### ISSUE TITLE
进阶-项目-经典街机游戏克隆-项目概述语句不通

### ISSUE THREAD

**Issue by liminjun** [udacity/fend-issues-zh#54]
问题描述：
**面向对象的编程是一种重要的编程范式，可影响你的应用程序架构并实现性能优化。** 
后半句语句不是非常通顺。
链接：https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/bae316ce-be90-4d30-b864-55d65207aa8c/lessons/2696458597239847/concepts/25968188800923

修改建议：
并实现性能优化可以去掉。

**Comment by evestorm** [comment]
已改善
