### ISSUE TITLE
进阶-项目-经典街机游戏克隆-项目说明文案统一

### ISSUE THREAD

**Issue by liminjun** [udacity/fend-issues-zh#55]
问题描述：
![image](https://user-images.githubusercontent.com/966009/35479350-15c23340-0430-11e8-9923-1e5e5e9ddbd2.png)

内容中敌人有的显示为Bug，有的显示Enemies。
修改建议：
因为程序里面也是Enemies，所以可以统一为Enemies。

**Comment by evestorm** [comment]
已优化！
