### ISSUE TITLE
进阶-经典街机游戏克隆-类和对象-课程9 -“this关键字”-添加超链接

### ISSUE THREAD

**Issue by GongJS** [udacity/fend-issues-zh#60]
![image](https://user-images.githubusercontent.com/25744301/35491827-013e221c-04e4-11e8-9493-d0d891d9a706.png)

“调用对象方法”，这里加一下目标超链接，提高体验度

**Comment by evestorm** [comment]
@GongJS 
这是一个历史遗留问题。由于一门nd会有多个版本，而不同版本下的同一节课的链接地址不同。所以不能在课程中“硬编码”此链接。这就导致一个隐患：V5版本的同学能够打开此链接，V4版本却无法正常跳转。
