### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by wqfeng** [udacity/fend-issues-zh#63]
https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/409c8e65-59c6-4d67-8ea8-6934fad5ab0b#

## 问题
第 2 课 将探讨 JavaScript 函数如何是 一级 函数。

## 建议

听起来很别扭，翻译成 **为何** 或 **为什么** 会更好一点吧

**Comment by wqfeng** [comment]
同一页面最后的小结部分：

> 在 JavaScript 中，对象是一个无序的属性集合。每个属性由一个键值对组成，并且既可以引用基元（例如字符串、数字、布尔值等），也可以引用其他对象。

**基元** 是什么？结合上下文应该是 **基本类型** 吧？

**Comment by evestorm** [comment]
@wqfeng 超棒的反馈！已修正！
