### ISSUE TITLE
进阶-街区地图 课程10 API入门 "你的项目"  图片无法正常显示

### ISSUE THREAD

**Issue by ghost** [udacity/fend-issues-zh#64]
课程链接：[你的项目](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/b4672613-0d5a-4fb9-bb2d-571c92361fee/modules/4fd8d440-9428-4de7-93c0-4dca17a36700/lessons/8304370457/concepts/2fb18c4e-5344-43e3-bb98-638a940e8158)

如图：
![wx20180130-131251](https://user-images.githubusercontent.com/25104361/35549923-df13d832-05c2-11e8-8b80-6d63673478b5.png)

课程图片无法显示。

**Comment by evestorm** [comment]
做该项目需要翻墙哦，先mark一下~ 暂时不解决。
