### ISSUE TITLE
进阶-经典街机游戏克隆-课程 2 焦点-什么是焦点

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#66]
![screen shot 2018-01-30 at 6 41 02 pm](https://user-images.githubusercontent.com/6949550/35562276-d6b593d0-05ed-11e8-88af-310970312a9f.png)
![screen shot 2018-01-30 at 6 42 32 pm](https://user-images.githubusercontent.com/6949550/35562280-daa6637a-05ed-11e8-89a4-12f81bf1a963.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962031279/concepts/79667514380923)

- ”header“ 在这里翻为 ”报头“ 似乎有点不合适。
- ”这是设计的原因“  改为 ”这是有意的“ 可能更容易理解一点？

**Comment by sylviasun916** [comment]
已处理，谢谢反馈！
