### ISSUE TITLE
进阶-经典街机游戏克隆-课程 2 焦点-体验焦点

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#67]
![screen shot 2018-01-30 at 6 54 10 pm](https://user-images.githubusercontent.com/6949550/35562652-fb81147c-05ee-11e8-8f23-8efad31183e2.png)
[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962031279/concepts/83088022340923)

文字没有翻译呀 😂

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
