### ISSUE TITLE
进阶-经典街机游戏克隆-课程 2 焦点-13 键盘设计模式

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#71]
![screen shot 2018-01-31 at 12 05 51 am](https://user-images.githubusercontent.com/6949550/35576802-dedcaa26-061a-11e8-83f5-cfba0697e3b7.png)

![screen shot 2018-01-31 at 12 06 01 am](https://user-images.githubusercontent.com/6949550/35576803-df7d988c-061a-11e8-8198-716830510998.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962031279/concepts/79631416290923)

如果没理解错的话，字幕中红框标出来的对应的应该是 [setAttribute() 方法](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/setAttribute)。

**Comment by sylviasun916** [comment]
已修改，谢谢
