### ISSUE TITLE
进阶-经典街机游戏克隆-类和对象-课程9 -原型继承-子类-习题2/4 答案有多余字符

### ISSUE THREAD

**Issue by GongJS** [udacity/fend-issues-zh#72]
![image](https://user-images.githubusercontent.com/25744301/35602040-0cb5841c-0671-11e8-9ad4-957d4b279e78.png)

这里的"后"是不是应该去掉？

**Comment by evestorm** [comment]
@GongJS 此处是漏掉了一个 “最” 字。已修正，超棒！
