### ISSUE TITLE
进阶-经典街机游戏克隆-课程 3 语义基础-7 角色、名称、值

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#77]
![screen shot 2018-02-01 at 11 30 16 pm](https://user-images.githubusercontent.com/6949550/35686755-fbef1be2-07a7-11e8-8089-8bb7f25d4dd4.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962141425/concepts/79650516410923)

字幕看起来不是很通顺。
可能字幕原文为 “We call this an element's role.“ ？
建议： “称之为元素的角色”。

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
