### ISSUE TITLE
进阶-经典街机游戏克隆-课程 3 语义基础-15 替代文本

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#79]
![screen shot 2018-02-01 at 11 59 30 pm](https://user-images.githubusercontent.com/6949550/35688427-1dfe07f8-07ac-11e8-89a9-5c79ab098d6c.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/7962141425/concepts/79591617440923)

- “报头” 似乎应翻为 “标题”

**Comment by sylviasun916** [comment]
已修改，谢谢
