### ISSUE TITLE
 PART 1 + Lesson 1 自选课程

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#8]
![tim 20180115185049](https://user-images.githubusercontent.com/7417557/34938986-2faf24f8-fa25-11e7-858e-61b0870e54bb.png)
[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8162118632/concepts/81926728850923](url)
描述：右上角点击EDIT跳转到首页，不知是不是正式上线时可以使用的功能
修改建议：添加可用链接或者删掉不必要的功能

**Comment by evestorm** [comment]
@eruerua 这个 `EDIT` 按钮可忽略哦，正常情况下再教室是看不到此按钮的~ 感谢反馈！
