### ISSUE TITLE
进阶-经典街机游戏克隆-课程 4 导航内容-2 使用屏幕阅读器浏览网页

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#80]
![screen shot 2018-02-02 at 12 24 06 am](https://user-images.githubusercontent.com/6949550/35689871-731051d0-07af-11e8-9072-c561f06fceae.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8079270944/concepts/81639702060923)

截图中红框的部分好像是多余的。

不过那一行整个似乎都不太通顺...

**Comment by evestorm** [comment]
已修正！
