### ISSUE TITLE
进阶-经典街机游戏克隆-课程 4 导航内容-10 标记

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#83]
![screen shot 2018-02-02 at 10 44 39 pm](https://user-images.githubusercontent.com/6949550/35738859-fee968f2-086a-11e8-8ef2-fc4b93da93c3.png)

![screen shot 2018-02-02 at 10 42 48 pm](https://user-images.githubusercontent.com/6949550/35738875-018a1b1a-086b-11e8-8b82-0026c144cfb7.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8079270944/concepts/81573813960923)

- 图一，箭头那里缺少一个词 “main"
- 图二，缺少一个词 ”header"

还有，这个视频的整个字幕好像都缺少了几个词语，不过在视频中讲师有指出来，看起来也还算连贯，不知是不是故意缺少那几个词语。

**Comment by sylviasun916** [comment]
原字幕都有 只是 vtt 格式在 AWS上不显示，很奇怪 。。。先修改一下，谢谢反馈！
