### ISSUE TITLE
进阶-经典街机游戏克隆-课程 4 导航内容-11 练习 标记

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#84]
[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8079270944/concepts/80813009720923)

![screen shot 2018-02-02 at 10 51 59 pm](https://user-images.githubusercontent.com/6949550/35739345-42276ae6-086c-11e8-94dd-14e3078a42b6.png)
缺少 “header” 一词

![screen shot 2018-02-02 at 10 53 14 pm](https://user-images.githubusercontent.com/6949550/35739388-5d91b48a-086c-11e8-8702-5162d362d390.png)
缺少 “main" 一词

![screen shot 2018-02-02 at 10 53 28 pm](https://user-images.githubusercontent.com/6949550/35739455-9e759340-086c-11e8-926d-aeb4f517d17a.png)
缺少 “aside” 一词

![screen shot 2018-02-02 at 10 53 38 pm](https://user-images.githubusercontent.com/6949550/35739502-bed51a2a-086c-11e8-98c4-7bfea0175c56.png)
缺少 “aside” 一词

![screen shot 2018-02-02 at 10 54 07 pm](https://user-images.githubusercontent.com/6949550/35739554-e7536c2c-086c-11e8-8f62-82e8ab6e9d93.png)
缺少 “main” 一词

![screen shot 2018-02-02 at 10 54 32 pm](https://user-images.githubusercontent.com/6949550/35739587-0325ae4c-086d-11e8-8739-0cefaf33426b.png)
缺少“article”一词

**Comment by sylviasun916** [comment]
已修改 谢谢反馈
