### ISSUE TITLE
入门：记忆游戏 课程21 使用浏览器事件

### ISSUE THREAD

**Issue by BrainChen** [udacity/fend-issues-zh#85]
### 课程1 简介
推荐的google事件文档在国内打不开。。。而且还是英文的
![kkfh2zg 5 uwzgy jumv0](https://user-images.githubusercontent.com/24735241/35787042-44aca136-0a66-11e8-813f-fd285ca630f7.png)
google提供了中文翻译的网址，并且可以墙内访问，建议将https://developers.google.com/web/tools/chrome-devtools/console/events#monitor_events
中`developers.google.com`替换成`developers.google.cn`
**所有相关链接也可以这样操作**

**Comment by evestorm** [comment]
哇！赞航航！已优化！
