### ISSUE TITLE
进阶-经典街机游戏克隆-课程街机游戏克隆-课程 5 ARIA-4 ARIA 有什么用？

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#86]
![screen shot 2018-02-05 at 10 18 00 pm](https://user-images.githubusercontent.com/6949550/35809143-c2c24b00-0ac2-11e8-8164-9ebd294bbbdf.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8311490720/concepts/83024007380923)

字幕中 “disclosure widget” 翻为 “披露小部件” 不是很好懂啊 😂

**Comment by sylviasun916** [comment]
已修改为 “公开小组件” ，谢谢反馈！
