### ISSUE TITLE
进阶-经典街机游戏克隆-课程街机游戏克隆-课程 5 ARIA-5 角色扮演

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#87]
![screen shot 2018-02-05 at 10 54 08 pm](https://user-images.githubusercontent.com/6949550/35810746-aeda1578-0ac7-11e8-8209-233cdfa65599.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8311490720/concepts/83024007390923)

字幕似乎不太通顺。
可能像这样 “大部分将是可选的通用全局属性”

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
