### ISSUE TITLE
进阶-经典街机游戏克隆-课程街机游戏克隆-课程 5 ARIA-10 默认语义和标记

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#88]
![screen shot 2018-02-05 at 11 33 35 pm](https://user-images.githubusercontent.com/6949550/35812885-21ac72c6-0acd-11e8-8158-fde73e6c71b6.png)

[课程链接](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8311490720/concepts/83024007410923)

文本内容没有翻译呢～

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
