### ISSUE TITLE
进阶-经典街机游戏克隆-课程7深入了解对象-3调用对象方法-习题1/6答案有问题

### ISSUE THREAD

**Issue by GongJS** [udacity/fend-issues-zh#89]
![image](https://user-images.githubusercontent.com/25744301/35845095-bec444ca-0b4b-11e8-99fe-edde70b0fb3c.png)

我写的这个答案在chrome浏览器上测试是没问题的，但是提交后系统说我的答案有误。

**Comment by sylviasun916** [comment]
@evestorm

**Comment by evestorm** [comment]
@GongJS 哈哈，你在 `;` 后面一定按下了回车键

**Comment by evestorm** [comment]
已修正正则匹配
