### ISSUE TITLE
PART 1 + Lesson 1 自选课程1 HTTP的请求和相应周期 练习7 配置

### ISSUE THREAD

**Issue by eruerua** [udacity/fend-issues-zh#9]
![2](https://user-images.githubusercontent.com/7417557/34939391-97599e0c-fa26-11e7-830f-c5aabd329aa8.png)
[https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/ff929c6d-f9cf-442e-a9d5-401333a28877/modules/b5610af8-674b-4254-9820-ab46fdfabb91/lessons/8162118632/concepts/af121247-7060-4993-a0ce-8bfc11400ddc](url)
问题描述:页面为英语
建议：翻译为中文，有部分学员尤其对全英文的页面排斥，从而影响学习。

**Comment by sylviasun916** [comment]
已修改，非常感谢反馈！！！
