### ISSUE TITLE
编写本 repo 的 issue template

### ISSUE THREAD

**Issue by weierz** [udacity/fend-issues-zh#90]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by evestorm** [comment]
66666，你咋发现这个仓库的？ @WillBeethoven

**Comment by weierz** [comment]
看见阿权 Star 了，哈哈

![screen shot 2018-02-06 at 17 00 01](https://user-images.githubusercontent.com/14329786/35850290-3c8ed128-0b5f-11e8-84fe-c83dddb881ec.png)

**Comment by evestorm** [comment]
【机智】

**Comment by weierz** [comment]
👍
![screen shot 2018-02-06 at 17 49 19](https://user-images.githubusercontent.com/14329786/35852516-1718f156-0b66-11e8-8a3f-1edfb2ecdb8b.png)
