### ISSUE TITLE
经典街机游戏克隆 5-17 字幕问题

### ISSUE THREAD

**Issue by jojojojoe** [udacity/fend-issues-zh#91]
进阶 > 经典街机游戏克隆 > 课程 5 ARIA > [17.Atomic、Relevant 与 Busy ](https://classroom.udacity.com/nanodegrees/nd001-cn-advanced/parts/2b2ac66f-163e-4b23-a2e6-c1f0f03e0b80/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8311490720/concepts/83024007440923)

![screen shot 2018-02-06 at 9 24 18 pm](https://user-images.githubusercontent.com/6949550/35862422-99fb6d40-0b86-11e8-8bee-870abf3effd2.png)

字幕中红框文字似乎应该是 aria-atomic

**Comment by sylviasun916** [comment]
已修改，谢谢反馈
