### ISSUE TITLE
【翻译问题】A Framework's Base Features

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#93]
## 课程导航+地址

https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084670183/concepts/70005164560923

## 截图
<img width="1174" alt="2018-02-08 11 36 24" src="https://user-images.githubusercontent.com/9304701/35981757-06b7958c-0d29-11e8-8c3c-e1f4eaabcce5.png">

## 具体描述
01:05s 的 `不只是`， 应该为 `只是`

**Comment by sylviasun916** [comment]
已修改，谢谢！
