### ISSUE TITLE
【页面问题】Constructor Function Quiz

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#94]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084670183/concepts/70958689530923

## 截图
<img width="1611" alt="2018-02-08 11 52 13" src="https://user-images.githubusercontent.com/9304701/35982569-1bef2a12-0d2b-11e8-83fa-f030fc5bff6f.png">

## 具体描述
练习题加载不出来

**Comment by PoBlue** [comment]
这链接也有同样问题，不知道是不是我这边的网络问题。。

https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084670183/concepts/70975885400923

**Comment by evestorm** [comment]
两处链接中的练习题都能够加载，网络问题....
