### ISSUE TITLE
【字幕问题】A Router & The Backbone.history Object

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#95]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084670183/concepts/70852885520923

## 截图

<img width="1611" alt="2018-02-09 12 06 27" src="https://user-images.githubusercontent.com/9304701/35983499-1b45a22e-0d2d-11e8-952e-e42c4bafa2db.png">

## 具体描述
00:50s：这里的字幕下面有个 17 ，有可能是字幕文件出问题了～

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
