### ISSUE TITLE
【字幕问题】Welcome to Angular

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#96]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7088388557/concepts/70707885650923

## 截图
<img width="1611" alt="2018-02-09 12 18 02" src="https://user-images.githubusercontent.com/9304701/35984178-d6633926-0d2e-11e8-9d50-a644bca647fd.png">

## 具体描述
00:35s -> 下面多了个数字，有可能是字幕格式问题

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
