### ISSUE TITLE
【翻译问题】Required ES6 Knowledge

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#97]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7026988599/concepts/71030985360923

## 截图
<img width="1611" alt="2018-02-09 2 44 10" src="https://user-images.githubusercontent.com/9304701/36015069-be6c5bee-0da7-11e8-83bf-9a8eff9316a2.png">

## 具体描述

00:12s 处的 `承诺` ，应该不翻译的，它指的是 [Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise), 一个函数来的

**Comment by sylviasun916** [comment]
已修改，谢谢！
