### ISSUE TITLE
【翻译问题】Generating a Route & Template

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#98]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7026988599/concepts/70922285440923

## 截图
<img width="1611" alt="2018-02-09 2 52 58" src="https://user-images.githubusercontent.com/9304701/36015382-2144c4b2-0da9-11e8-9d79-4e610b931c3d.png">

## 具体描述
00:57 -> `练习` 应改为 `测试`

**Comment by evestorm** [comment]
@sylviasun916

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
