### ISSUE TITLE
【翻译问题】The Service Worker Lifecycle

### ISSUE THREAD

**Issue by PoBlue** [udacity/fend-issues-zh#99]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/83c4bddc-b362-4e71-8fa1-91f30ba57ab0/lessons/6381510081/concepts/63885494300923

## 截图
<img width="1639" alt="2018-02-09 4 34 01" src="https://user-images.githubusercontent.com/9304701/36018550-1d56a074-0db7-11e8-94b6-506dad97f3d7.png">

## 具体描述
01:04 -> `页面加载时` 改为 `页面加载后才` 会好些

**Comment by PoBlue** [comment]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/83c4bddc-b362-4e71-8fa1-91f30ba57ab0/lessons/6381510081/concepts/63885494300923

## 截图

<img width="1639" alt="2018-02-09 4 45 37" src="https://user-images.githubusercontent.com/9304701/36019529-8c28b0c0-0dba-11e8-8f66-224b170b21ed.png">



## 具体描述
02:04 -> `这是由之前看到的窗口客户端之间的重叠造成的` 改为 `像之前的演示 这是由窗口客户端之间的重叠造成的` 会好些

**Comment by evestorm** [comment]
@sylviasun916

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
